version: '2'

services:

# Chathost and APIs
  chathost:
    image: 'node:16'
    container_name: chathost
    restart: always
    working_dir: /usr/src
    command: [ 'node', 'index.js' ]
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment:
      - CHATHOST_PORT=2820
      - CHATHOST_LOGGING=console
      - CHATHOST_ADMIN=admin
      - CHATHOST_ADMINPASSWORD=${MASTERPASSWORD}
      - CHATHOST_BOLT=https://bolt.${URL}
    ports:
      - '2820:2820/tcp'
    volumes:
      - ./src:/usr/src
      - ./node_modules:/usr/src/node_modules
      - /tmp:/tmp
